### ISSUE TITLE
Can't initialize parallel_sampler after tf-session setup

### ISSUE THREAD

**Issue by zequnyu** [rlworkgroup/garage#1076] opened 2019-11-26 20:38 UTC
If we move `parallel_sampler` initialization anywhere after `Runner.__init__()` (before session setup), this test will fail:
https://github.com/rlworkgroup/garage/blob/c610192bb9f35d183edcf2f41667578716e133cc/tests/garage/sampler/test_sampler.py#L30

Error message I got was:
```
src/garage/experiment/local_runner.py:185: in _start_worker
    self._sampler.start_worker()
src/garage/tf/samplers/batch_sampler.py:52: in start_worker
    parallel_sampler.populate_task(self.env, self.algo.policy)
src/garage/sampler/parallel_sampler.py:79: in populate_task
    singleton_pool.n_parallel)
src/garage/sampler/stateful_pool.py:75: in run_each
    return results.get()
```

**Comment by zequnyu** [comment] 2019-11-26 20:38
@krzentner

**Comment by zequnyu** [comment] 2019-11-26 20:40
@naeioi Would you comment on this? KR wants more investigation.

**Comment by krzentner** [comment] 2019-11-26 21:32
Okay, I looked into this a little bit more, so I think I understand now why it's hard.

We'll just leave this alone for now. Perhaps we'll move to TensorFlow 2 before it's worth fixing.

**Comment by naeioi** [comment] 2019-11-26 22:58
Do you have a reproducer I can try? @zequnyu

**Comment by zequnyu** [comment] 2019-11-27 03:37
This is not a bug, it just demonstrates the difficulty to initialize parallel_sampler after tf-session initialization. To reproduce this, move this https://github.com/rlworkgroup/garage/blob/556dc3a12c68a3f1f2431523e2ee258893cdb909/src/garage/experiment/local_runner.py#L123

to `runner.setup()`.

**Comment by zhanpenghe** [comment] 2020-04-24 16:31
Hey I am wondering if there is any update on this issue? One of my collaborator is encountering similar things using gpu with `BatchSampler`.  I think this is due to the session is not set up.

**Comment by zhanpenghe** [comment] 2020-04-24 16:34
If this is not going to be fixed soon, should I use Ray sampler instead? I have never used it and not sure about how it is comparing to the old sampler while using GPU(s).

**Comment by ryanjulian** [comment] 2020-04-24 20:14
I think @krzentner has been focusing on eliminating `BatchSampler `and other `stateful_pool`-based samplers in favor of the newer sampler interface. Basically, we've been hoping to delete `BatchSampler` before having to fix this bug.

For something close to `BatchSampler`, I think the recently-committed [`MultiprocessingSampler`](https://github.com/rlworkgroup/garage/blob/master/src/garage/sampler/multiprocessing_sampler.py) will be nearly indistinguishable. `RaySampler` is also an option and has been used successfully with a ton of experiments in our recent paper. We have both because `ray` has a larger memory footprint and is a huge dependency which many people probably don't want.

Note that the new sampler interface has a distinction between the backend (`Sampler`) and frontend (`Worker`). Within the new setup, we would says that `BatchSampler` can be represented by the tuple `(MultiprocessingSampler, DefaultWorker)`, because it schedules `DefaultWorker`'s across multiple processes managed by `multiprocessing`. The `DefaultWorker` is just your plain, boring old "run rollout using the env and policy" loop, and it's what `LocalRunner` uses if you don't specify otherwise.

The `Worker` interface exists because sometimes we have to change sampling with an alternative process or rollout function, e.g. in the case of PEARL or Task Embeddings or RL2, in which case those algorithms can redefine what happens during a rollout by providing and alternative Worker. Workers can do much more than that (e.g. task sampling in meta-RL),  but redefining `rollout` a little bit is the most common reason.

You can have your worker initialize TF or the GPU however you'd like. I think if you wrap [`DefaultWorker`](https://github.com/rlworkgroup/garage/blob/master/src/garage/samplers/worker.py) with the [`TFWorkerWrapper`](https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/samplers/worker.py) it does the initialization for you.

If you are running small-scale experiments, or just want to try something simple to make sure your `Worker` is working, you can use `LocalSampler` which is literally a blocking call to `rollout`, e.g. `(LocalSampler, DefaultWorker)` is equivalent to just running `rollout` directly in your training loop.

Perhaps what's really missing here is a good example. 

Here's an example from RL2 for how to use a custom sampler and worker: https://github.com/rlworkgroup/garage/blob/master/examples/tf/rl2_ppo_halfcheetah_meta_test.py

Here's an [example of how to use `RaySampler`](https://github.com/rlworkgroup/garage/blob/master/examples/tf/trpo_swimmer_ray_sampler.py). Note that because we don't need to change anything about `rollout`, we don't specify a worker in `runner.setup` and it uses `DefaultWorker` for us.

If you are using `runner.obtain_samples()` to get your samples in your algorithm, you don't need to change any code on the algorithm side to use these new samplers. For instance, [here](https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/algos/rl2.py#L322) is the main sampling step in RL2.

If you want vectorization *inside* your worker, e.g. the equivalent of `parallel_sampler`/`parallel_vec_env_executor`, you will have to patch in #1311 , or just wait for it to hit master in a few hours. If you're building forward-looking code and plan on tracking master, I recommend you use the new samplers. We plan on deleting the old ones basically as soon as we can after the release.

**Comment by ryanjulian** [comment] 2020-04-24 20:14
@krzentner may also have some helpful comments

**Closed** 2020-09-01 20:57 UTC
Labels: tf
