### ISSUE TITLE
Categorical MLP policy for pytorch

### ISSUE THREAD

**Issue by chelseas** [rlworkgroup/garage#1796] opened 2020-07-24 19:01 UTC
In order to have a complete set of tools for developing in torch, the library needs a categorical policy class for torch. Right now it only has policy classes for outputting continuous actions.

**Comment by ryanjulian** [comment] 2020-07-24 20:01
@chelseas Thanks for filing an issue.

This is a duplicate of #1273 and #1324 so I will close it. You can see both of those are issues are in the 2020.09 milestones, which means we intend to finish them in time for a September release.

If you are in immediate need of a CategoricalMLPPolicy in torch, the implementation is fairly formulaic by porting the TF implementation.

See:

GaussianMLPPolicy in TF:
https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/policies/gaussian_mlp_policy.py
GaussianMLPPolicy in Torch:
https://github.com/rlworkgroup/garage/blob/master/src/garage/torch/policies/gaussian_mlp_policy.py#L9
CategoricalMLPPolicy in TF:
https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/policies/categorical_mlp_policy.py

**Comment by ryanjulian** [comment] 2020-07-24 20:01
See also #1605

**Closed by ryanjulian** 2020-07-24 20:01 UTC
Labels: duplicate
