### ISSUE TITLE
TRPO performance has a regression

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1180] opened 2020-02-28 19:15 UTC

**Comment by naeioi** [comment] 2020-03-30 01:30
Preliminary benchmarks on InvertedDoublePendulum shows a close performance between garage and OpenAI baselines.

https://tensorboard.dev/experiment/OhevZaJWRqGK4ZToaYYRfw/#scalars&runSelectionState=eyJnYXJhZ2UiOnRydWUsImdhcmFnZV9weXRvcmNoIjp0cnVlfQ%3D%3D

**Comment by naeioi** [comment] 2020-04-01 00:22
Benchmark results on MuJoCo3M. The rest of the tasks are on their way...

![Hopper-v2_benchmark](https://user-images.githubusercontent.com/8409272/78086815-ee059d00-7373-11ea-8cd5-1c44f5ab6e3f.png)
![InvertedDoublePendulum-v2_benchmark](https://user-images.githubusercontent.com/8409272/78086817-ee9e3380-7373-11ea-9813-0ee0e022b166.png)
![InvertedPendulum-v2_benchmark](https://user-images.githubusercontent.com/8409272/78086818-ee9e3380-7373-11ea-8552-797f31d11ec4.png)
![HalfCheetah-v2_benchmark](https://user-images.githubusercontent.com/8409272/78086819-ef36ca00-7373-11ea-9a79-3b663d860244.png)

**Comment by ryanjulian** [comment] 2020-04-01 00:43
Do you plan on running torch TRPO too?

**Comment by naeioi** [comment] 2020-04-13 07:11
Benchmark results of TensorFlow, PyTorch, and OpenAI baselines.

In all cases except Reacher, garage is better than baselines in terms of the final return value. 

Overall, TRPO does not have a performance regression, so I will close this issue. The difference between garage and baselines on Reacher is worth a future inspection. This issue might not be restricted to TRPO, but other algorithms in general, because garage Tensorflow and garage PyTorch diverge from baselines in a similar pattern. 

![Reacher-v2_benchmark](https://user-images.githubusercontent.com/8409272/79100036-519bad00-7d1a-11ea-9cac-3f1c89a05c4e.png)
![Swimmer-v2_benchmark](https://user-images.githubusercontent.com/8409272/79100039-52344380-7d1a-11ea-8a38-3b44a052c0e6.png)
![Walker2d-v2_benchmark](https://user-images.githubusercontent.com/8409272/79100040-52ccda00-7d1a-11ea-8a0b-7430804b9811.png)
![InvertedDoublePendulum-v2_benchmark](https://user-images.githubusercontent.com/8409272/79100041-52ccda00-7d1a-11ea-807a-6c450f5ddd9d.png)
![InvertedPendulum-v2_benchmark](https://user-images.githubusercontent.com/8409272/79100042-53657080-7d1a-11ea-8223-272f9bf16635.png)
![HalfCheetah-v2_benchmark](https://user-images.githubusercontent.com/8409272/79100045-53657080-7d1a-11ea-9f28-99e84c9b61af.png)
![Hopper-v2_benchmark](https://user-images.githubusercontent.com/8409272/79100046-53fe0700-7d1a-11ea-9e74-f2e4e7acfff9.png)

**Closed by naeioi** 2020-04-13 07:11 UTC
Labels: bug, needs backport

**Comment by ryanjulian** [comment] 2020-04-14 03:37
Thanks for the excellent work @naeioi !
