### ISSUE TITLE
Am I missing something or is everything broken?

### ISSUE THREAD

**Issue by half-potato** [rlworkgroup/garage#388] opened 2018-11-11 11:05 UTC
There isn't even an \_\_init\_\_.py in garage so running setup.py install doesn't install anything. None of the environments are even registered with openai gym. Like what is even going on?

**Comment by half-potato** [comment] 2018-11-11 11:47
https://github.com/half-potato/garage This is what working code looks like. I don't have full coverage of all of the environments yet because I don't need them right now.

**Comment by half-potato** [comment] 2018-11-11 11:52
Like you guys seem smart you have a lot of fancy tools so I

**Comment by ryanjulian** [comment] 2018-11-11 14:48
Hi Alex,

Thanks for trying out garage! I took a look at your fork.

To directly address your issue: to our knowledge, everything is not broken. Our CI is green and we have many machines running both `master` and the `v2018.10` release.

Likely, something is broken and we don't know about it. To help us, we ask bug reporters provide a minimal script which reproduces a bug or error, when run on a supported platform (Ubuntu 16.04 and recent versions of OS X), from an environment created using the [installation instructions](https://rlgarage.readthedocs.io/en/latest/user/installation.html#express-install). We find that's the fastest way to get to the root of an issue.

## Platform support
I'm realizing now that our platform support is not well-documented in the README.md nor the documentation, so I will update that now. In short, we officially support Ubuntu 16.04 and the most recent version of MacOS. We will add official Ubuntu 18.04 support in the next few weeks.

All other support is best-effort, i.e. we will always accept high-quality PRs for supporting different platforms, but we may or may not test those in our CI. In addition to Ubuntu 16.04 and MacOS 10.14, myself and people I work with have working installations (with little or no hacking required) on Ubuntu 18.04 and several recent versions of MacOS.

## Some comments on packaging/installation
* pip package
    We don't currently use pip or a proper setup.py for installation of the garage package itself, and instead use conda, as mentioned in the [installation instructions](https://rlgarage.readthedocs.io/en/latest/user/installation.html#express-install).

    You have noticed that setup.py still exists but is bare--we currently use it only for installing an egg-link (e.g. `pip install -e .`) from the garage repository into a conda environment to make garage importable from within the conda environment. The setup scripts in `scripts/setup_macos.sh` and `scripts/setup_linux.sh` will install the conda environment for you, or you can read them as a guide if you'd like to get up-and-running manually.

    We're personally not big fans of conda, but it works today and solves some challenging packaging problems. We are actively pursuing different packaging strategies, including a Pipenv and/or a vanilla pip package (or family thereof). Packaging is a major area of work for us right now and we'd love your contributions to a new packaging strategy, install procedure, expanded platform support, etc.

* `__init__.py`
    `__init__.py` [is not required for Python package resolution since Python 3.3+](https://www.python.org/dev/peps/pep-0420/) (we support only Python 3.5+), which is why we omit empty `__init__.py` files in some packages.

* Gym registration of environments
   Most environments in garage were designed to be used from within garage, though we also expect people to use them outside, which is why we rewrote them to use the `gym.Env` interface.

    There is not really a need to use the `gym.make` factory interface to construct garage environment--you can just construct each environment as a normal Python object and run it with any algorithm which supports objects constructed by `gym.make`. This is relevant since some of our environments have meaningful constructor parameters, which can't be readily supported by the `gym.make` interface.

    We recognize that some users would like to use the `gym.make` interface, and are communicating with the OpenAI gym maintainers about whether they intend downstream packages to use the registration API.

    We are also pursuing moving our custom environments (and other parts of garage) into their own separately-installable pip package, since not everyone wants the kitchen sink.

**Comment by half-potato** [comment] 2018-11-12 00:34
Do any of you use the garage package outside of garage? I don't think it's possible to do so without a proper setup. I used conda and it did not install the package in a way that allowed it to be imported from another environment.

**Comment by half-potato** [comment] 2018-11-12 00:45
Okay, so not everything is broken. Just the entire packaging thing. It's so weird seeing something calling itself a framework but not being an actual package.

**Comment by ryanjulian** [comment] 2018-11-12 22:19
The pattern most people currently use is to create their own repository and check it out as a submodule in garage/sandbox. Then custom code lives at the package path `sandbox.mypackage`.

For examples, see:
https://github.com/ryanjulian/embed2learn
https://github.com/haarnoja/sac (based on the older rllab, same pattern)

We agree that this is not a great way to make a framework, and makes adoption hard. In fact, we discuss extensively in our latest [release notes](https://github.com/rlworkgroup/garage/releases/tag/v2018.10.0) how our biggest priority over the next few months is to repackage garage into non-monolithic components. I'll take your feedback as confirmation that this is the right path to be pursuing.

If you're interested in using the software, we'd love your input. What do you want to use garage for, and how could garage be better for that?

You seem to know a thing or two about Python packaging best practices. We'd love to have your help doing this the right way!

**Comment by ryanjulian** [comment] 2018-11-28 23:06
@half-potato would you mind if we closed this issue?

**Comment by ryanjulian** [comment] 2018-12-04 18:52
Closing since I haven't heard from @half-potato

**Closed by ryanjulian** 2018-12-04 18:52 UTC
Labels: question
