### ISSUE TITLE
Error when running examples/theano/trpo_cartpole_recurrent.py

### ISSUE THREAD

**Issue by jonashen** [rlworkgroup/garage#170] opened 2018-07-11 00:00 UTC
Potential lasagne error.

```
  File "/Users/jonathon/Documents/garage/garage/garage/policies/gaussian_gru_policy.py", line 51, in __init__
    output_nonlinearity=output_nonlinearity,
  File "/Users/jonathon/Documents/garage/garage/garage/core/network.py", line 263, in __init__
    b=l_output_flat.b,
  File "/anaconda2/envs/garage/lib/python3.5/site-packages/lasagne/layers/dense.py", line 78, in __init__
    super(DenseLayer, self).__init__(incoming, **kwargs)
  File "/anaconda2/envs/garage/lib/python3.5/site-packages/lasagne/layers/base.py", line 44, in __init__
    if any(d is not None and d <= 0 for d in self.input_shape):
  File "/anaconda2/envs/garage/lib/python3.5/site-packages/lasagne/layers/base.py", line 44, in <genexpr>
    if any(d is not None and d <= 0 for d in self.input_shape):
TypeError: unorderable types: tuple() <= int()
```

**Comment by ryanjulian** [comment] 2018-07-12 18:52
Duplicate of #182

**Closed by ryanjulian** 2018-07-12 18:52 UTC
Labels: bug, duplicate
