### ISSUE TITLE
box2d_env.py with plot=True raises NotImplementedError

### ISSUE THREAD

**Issue by jonashen** [rlworkgroup/garage#114] opened 2018-06-29 02:17 UTC
Currently when running `examples/trpo_cartpole.py` with `plot=True`, the `render()` function in `box2d_env.py` raises a NotImplementedError on line 358. 

However, commenting out both lines 357 and 358 will fix this issue and correctly draw the plot. This issue is being opened because the potential ramifications for commenting out these lines is unclear.

One potential reason for this new bug could be due to upgrading gym to v0.10, but unclear.

**Comment by ryanjulian** [comment] 2018-06-29 18:21
Duplicate of #93

**Closed by ryanjulian** 2018-06-29 18:21 UTC
Labels: bug, duplicate, question
