### ISSUE TITLE
docker: build-headless broken

### ISSUE THREAD

**Issue by tunglm2203** [rlworkgroup/garage#581] opened 2019-03-12 04:37 UTC
I built garage on local PC using command: _make build-headless_
OS: Ubuntu 16.04
It's broken at step 18, here is screen log:

Step 17/22 : ARG MJKEY
 ---> Running in 6a106b593221
Removing intermediate container 6a106b593221
 ---> 493a5100d3e4
Step 18/22 : RUN touch /root/.mujoco/mjkey.txt &&   conda env create -f /root/code/garage/environment.yml &&   rm -rf /opt/conda/pkgs/* &&   rm /root/.mujoco/mjkey.txt
 ---> Running in a01a265761a8
Collecting package metadata: ...working... done
Solving environment: ...working... done

Downloading and Extracting Packages
virtualenv-16.0.0    | 1.8 MB    | ########## | 100% 
zlib-1.2.11          | 101 KB    | ########## | 100% 
libgfortran-3.0.0    | 281 KB    | ########## | 100% 
setuptools-40.8.0    | 626 KB    | ########## | 100% 
six-1.12.0           | 22 KB     | ########## | 100% 
openssl-1.0.2r       | 3.1 MB    | ########## | 100% 
sqlite-3.26.0        | 1.9 MB    | ########## | 100% 
libffi-3.2.1         | 46 KB     | ########## | 100% 
toml-0.10.0          | 16 KB     | ########## | 100% 
pyyaml-3.13          | 177 KB    | ########## | 100% 
numpy-1.14.5         | 9.0 MB    | ########## | 100% 
readline-7.0         | 391 KB    | ########## | 100% 
libgcc-ng-7.3.0      | 6.1 MB    | ########## | 100% 
wheel-0.33.1         | 34 KB     | ########## | 100% 
ca-certificates-2019 | 146 KB    | ########## | 100% 
editdistance-0.5.3   | 26 KB     | ########## | 100% 
pip-19.0.3           | 1.8 MB    | ########## | 100% 
importlib_metadata-0 | 31 KB     | ########## | 100% 
aspy.yaml-1.2.0      | 6 KB      | ########## | 100% 
xz-5.2.4             | 366 KB    | ########## | 100% 
python-3.6.6         | 29.0 MB   | ########## | 100% 
zipp-0.3.3           | 6 KB      | ########## | 100% 
yaml-0.1.7           | 78 KB     | ########## | 100% 
blas-1.1             | 1 KB      | ########## | 100% 
openblas-0.2.20      | 17.0 MB   | ########## | 100% 
nodeenv-1.3.3        | 27 KB     | ########## | 100% 
libstdcxx-ng-7.3.0   | 2.6 MB    | ########## | 100% 
cached-property-1.5. | 10 KB     | ########## | 100% 
tk-8.6.9             | 3.1 MB    | ########## | 100% 
importlib_resources- | 36 KB     | ########## | 100% 
cfgv-1.5.0           | 10 KB     | ########## | 100% 
ncurses-6.1          | 1.3 MB    | ########## | 100% 
certifi-2019.3.9     | 149 KB    | ########## | 100% 
pre_commit-1.14.4    | 176 KB    | ########## | 100% 
identify-1.4.0       | 74 KB     | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

CondaEnvException: Pip subcommand failed with 
output: Obtaining file:///root/code/garage (from -r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
Obtaining file:///root/code/garage (from -r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 2))
Collecting metaworlds from git+https://github.com/rlworkgroup/metaworlds.git@master#egg=metaworlds (from -r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 3))
  Cloning https://github.com/rlworkgroup/metaworlds.git (to revision master) to /tmp/pip-install-7s84rqhq/metaworlds
Collecting viskit from git+https://github.com/rlworkgroup/viskit.git@master#egg=viskit (from -r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 4))
  Cloning https://github.com/rlworkgroup/viskit.git (to revision master) to /tmp/pip-install-7s84rqhq/viskit
Collecting akro@ https://api.github.com/repos/rlworkgroup/akro/tarball/ec846114881edef66a5ebdfffdcca9bee01d3aef from https://api.github.com/repos/rlworkgroup/akro/tarball/ec846114881edef66a5ebdfffdcca9bee01d3aef (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://api.github.com/repos/rlworkgroup/akro/tarball/ec846114881edef66a5ebdfffdcca9bee01d3aef
Collecting boto3 (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cc/bc/7ea267ec47027d63a76d447591e3b10f62d2a799bf418145dd61f5dbc70f/boto3-1.9.112-py2.py3-none-any.whl (128kB)
Requirement already satisfied: cached_property in /opt/conda/envs/garage/lib/python3.6/site-packages (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1)) (1.5.1)
Collecting cloudpickle (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/47/d5/efa7cacef5d3bdcd71d7053a698fb9b64a20fff5cb3c592efefa53ea5578/cloudpickle-0.8.0-py2.py3-none-any.whl
Collecting cma==1.1.06 (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c5/92/00c83a5e76b8941426b2bab66a035870b94fd83bb42db3d083d273a7fbdb/cma-1.1.06.tar.gz (108kB)
Collecting dm_control@ https://api.github.com/repos/deepmind/dm_control/tarball/92f9913013face0468442cd0964d5973ea2089ea from https://api.github.com/repos/deepmind/dm_control/tarball/92f9913013face0468442cd0964d5973ea2089ea (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://api.github.com/repos/deepmind/dm_control/tarball/92f9913013face0468442cd0964d5973ea2089ea
Collecting gym[all]==0.10.11 (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/87/04/70d4901b7105082c9742acd64728342f6da7cd471572fd0660a73f9cfe27/gym-0.10.11.tar.gz (1.5MB)
Collecting hyperopt (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/63/12/704382c3081df3ae3f9d96fe6afb62efa2fa9749be20c301cd2797fb0b52/hyperopt-0.1.2-py3-none-any.whl (115kB)
Collecting jsonmerge (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/e5/d8/f06bd65469b25010ff4b924fbd09a8f2a849325cbce947f56516858df17e/jsonmerge-1.5.2.tar.gz
Collecting joblib<0.13,>=0.12 (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/69/91/d217cec1fe6eac525ca964cd67e4f79b1d4ce68b64cb82d0b9ae1af2311e/joblib-0.12.5-py2.py3-none-any.whl (275kB)
Collecting matplotlib (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/e9/69/f5e05f578585ed9935247be3788b374f90701296a70c8871bcd6d21edb00/matplotlib-3.0.3-cp36-cp36m-manylinux1_x86_64.whl (13.0MB)
Collecting mujoco-py<1.50.2,>=1.50.1 (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cf/8c/64e0630b3d450244feef0688d90eab2448631e40ba6bdbd90a70b84898e7/mujoco-py-1.50.1.68.tar.gz (120kB)
Requirement already satisfied: numpy==1.14.5 in /opt/conda/envs/garage/lib/python3.6/site-packages (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1)) (1.14.5)
Collecting pandas (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/e6/de/a0d3defd8f338eaf53ef716e40ef6d6c277c35d50e09b586e170169cdf0d/pandas-0.24.1-cp36-cp36m-manylinux1_x86_64.whl (10.1MB)
Collecting polling (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a1/42/d11fca25b8ee038233bfabdd3dc89c92ce69f551fd9605093570bdfa7f89/polling-0.3.0.tar.gz
Collecting protobuf (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c5/60/ca38e967360212ddbb004141a70f5f6d47296e1fba37964d8ac6cb631921/protobuf-3.7.0-cp36-cp36m-manylinux1_x86_64.whl (1.2MB)
Collecting psutil (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/2f/b8/11ec5006d2ec2998cb68349b8d1317c24c284cf918ecd6729739388e4c56/psutil-5.6.1.tar.gz (427kB)
Collecting pyprind (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/1e/30/e76fb0c45da8aef49ea8d2a90d4e7a6877b45894c25f12fb961f009a891e/PyPrind-2.11.2-py3-none-any.whl
Collecting python-dateutil (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
Collecting scikit-image (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/24/06/d560630eb9e36d90d69fe57d9ff762d8f501664ce478b8a0ae132b3c3008/scikit_image-0.14.2-cp36-cp36m-manylinux1_x86_64.whl (25.3MB)
Collecting scipy (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7f/5f/c48860704092933bf1c4c1574a8de1ffd16bf4fde8bab190d747598844b2/scipy-1.2.1-cp36-cp36m-manylinux1_x86_64.whl (24.8MB)
Collecting tensorboard (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/0f/39/bdd75b08a6fba41f098b6cb091b9e8c7a80e1b4d679a581a0ccd17b10373/tensorboard-1.13.1-py3-none-any.whl (3.2MB)
Collecting tensorflow<1.13,>=1.12.0 (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/22/cc/ca70b78087015d21c5f3f93694107f34ebccb3be9624385a911d4b52ecef/tensorflow-1.12.0-cp36-cp36m-manylinux1_x86_64.whl (83.1MB)
Collecting tensorflow-probability<0.6.0,>=0.5.0 (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a1/ca/6f213618b5f7d0bf6139e6ec928d412a5ca14e4776adfd41a59c74a34021/tensorflow_probability-0.5.0-py2.py3-none-any.whl (680kB)
Collecting baselines@ https://api.github.com/repos/openai/baselines/tarball/f2729693253c0ef4d4086231d36e0a4307ec1cb3 from https://api.github.com/repos/openai/baselines/tarball/f2729693253c0ef4d4086231d36e0a4307ec1cb3 (from rlgarage==2019.6.0.dev0->-r /root/code/garage/condaenv.3t3eiQ.requirements.txt (line 2))
  Downloading https://api.github.com/repos/openai/baselines/tarball/f2729693253c0ef4d4086231d36e0a4307ec1cb3

error: ++ /opt/conda/bin/conda shell.posix hook
+ eval 'export CONDA_EXE="/opt/conda/bin/conda"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause

__conda_hashr() {
    if [ -n "${ZSH_VERSION:+x}" ]; then
        \rehash
    elif [ -n "${POSH_VERSION:+x}" ]; then
        :  # pass
    else
        \hash -r
    fi
}

__conda_activate() {
    if [ -n "${CONDA_PS1_BACKUP:+x}" ]; then
        # Handle transition from shell activated with conda <= 4.3 to a subsequent activation
        # after conda updated to >= 4.4. See issue #6173.
        PS1="$CONDA_PS1_BACKUP"
        \unset CONDA_PS1_BACKUP
    fi

    \local cmd="$1"
    shift
    \local ask_conda
    ask_conda="$(PS1="$PS1" "$CONDA_EXE" shell.posix "$cmd" "$@")" || \return $?
    \eval "$ask_conda"
    __conda_hashr
}

__conda_reactivate() {
    \local ask_conda
    ask_conda="$(PS1="$PS1" "$CONDA_EXE" shell.posix reactivate)" || \return $?
    \eval "$ask_conda"
    __conda_hashr
}

conda() {
    if [ "$#" -lt 1 ]; then
        "$CONDA_EXE"
    else
        \local cmd="$1"
        shift
        case "$cmd" in
            activate|deactivate)
                __conda_activate "$cmd" "$@"
                ;;
            install|update|upgrade|remove|uninstall)
                "$CONDA_EXE" "$cmd" "$@" && __conda_reactivate
                ;;
            *) "$CONDA_EXE" "$cmd" "$@" ;;
        esac
    fi
}

if [ -z "${CONDA_SHLVL+x}" ]; then
    \export CONDA_SHLVL=0
    PATH="$(dirname "$(dirname "$CONDA_EXE")")/condabin:${PATH:-}"
    \export PATH

    # We'\''re not allowing PS1 to be unbound. It must at least be set.
    # However, we'\''re not exporting it, which can cause problems when starting a second shell
    # via a first shell (i.e. starting zsh from bash).
    if [ -z "${PS1+x}" ]; then
        PS1=
    fi
fi

conda activate base'
++ export CONDA_EXE=/opt/conda/bin/conda
++ CONDA_EXE=/opt/conda/bin/conda
++ '[' -z '' ']'
++ export CONDA_SHLVL=0
++ CONDA_SHLVL=0
++++ dirname /opt/conda/bin/conda
+++ dirname /opt/conda/bin
++ PATH=/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin
++ export PATH
++ '[' -z '' ']'
++ PS1=
++ conda activate base
++ '[' 2 -lt 1 ']'
++ local cmd=activate
++ shift
++ case "$cmd" in
++ __conda_activate activate base
++ '[' -n '' ']'
++ local cmd=activate
++ shift
++ local ask_conda
+++ PS1=
+++ /opt/conda/bin/conda shell.posix activate base
++ ask_conda='PS1='\''(base) '\''
\export CONDA_DEFAULT_ENV='\''base'\''
\export CONDA_EXE='\''/opt/conda/bin/conda'\''
\export CONDA_PREFIX='\''/opt/conda'\''
\export CONDA_PROMPT_MODIFIER='\''(base) '\''
\export CONDA_PYTHON_EXE='\''/opt/conda/bin/python'\''
\export CONDA_SHLVL='\''1'\''
\export PATH='\''/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin'\'''
++ eval 'PS1='\''(base) '\''
\export CONDA_DEFAULT_ENV='\''base'\''
\export CONDA_EXE='\''/opt/conda/bin/conda'\''
\export CONDA_PREFIX='\''/opt/conda'\''
\export CONDA_PROMPT_MODIFIER='\''(base) '\''
\export CONDA_PYTHON_EXE='\''/opt/conda/bin/python'\''
\export CONDA_SHLVL='\''1'\''
\export PATH='\''/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin'\'''
+++ PS1='(base) '
+++ export CONDA_DEFAULT_ENV=base
+++ CONDA_DEFAULT_ENV=base
+++ export CONDA_EXE=/opt/conda/bin/conda
+++ CONDA_EXE=/opt/conda/bin/conda
+++ export CONDA_PREFIX=/opt/conda
+++ CONDA_PREFIX=/opt/conda
+++ export 'CONDA_PROMPT_MODIFIER=(base) '
+++ CONDA_PROMPT_MODIFIER='(base) '
+++ export CONDA_PYTHON_EXE=/opt/conda/bin/python
+++ CONDA_PYTHON_EXE=/opt/conda/bin/python
+++ export CONDA_SHLVL=1
+++ CONDA_SHLVL=1
+++ export PATH=/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin
+++ PATH=/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin
++ __conda_hashr
++ '[' -n '' ']'
++ '[' -n '' ']'
++ hash -r
+ conda activate /opt/conda/envs/garage
+ '[' 2 -lt 1 ']'
+ local cmd=activate
+ shift
+ case "$cmd" in
+ __conda_activate activate /opt/conda/envs/garage
+ '[' -n '' ']'
+ local cmd=activate
+ shift
+ local ask_conda
++ PS1='(base) '
++ /opt/conda/bin/conda shell.posix activate /opt/conda/envs/garage
+ ask_conda='PS1='\''(garage) '\''
\export CONDA_DEFAULT_ENV='\''garage'\''
\export CONDA_PREFIX='\''/opt/conda/envs/garage'\''
\export CONDA_PREFIX_1='\''/opt/conda'\''
\export CONDA_PROMPT_MODIFIER='\''(garage) '\''
\export CONDA_SHLVL='\''2'\''
\export PATH='\''/opt/conda/envs/garage/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin'\'''
+ eval 'PS1='\''(garage) '\''
\export CONDA_DEFAULT_ENV='\''garage'\''
\export CONDA_PREFIX='\''/opt/conda/envs/garage'\''
\export CONDA_PREFIX_1='\''/opt/conda'\''
\export CONDA_PROMPT_MODIFIER='\''(garage) '\''
\export CONDA_SHLVL='\''2'\''
\export PATH='\''/opt/conda/envs/garage/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin'\'''
++ PS1='(garage) '
++ export CONDA_DEFAULT_ENV=garage
++ CONDA_DEFAULT_ENV=garage
++ export CONDA_PREFIX=/opt/conda/envs/garage
++ CONDA_PREFIX=/opt/conda/envs/garage
++ export CONDA_PREFIX_1=/opt/conda
++ CONDA_PREFIX_1=/opt/conda
++ export 'CONDA_PROMPT_MODIFIER=(garage) '
++ CONDA_PROMPT_MODIFIER='(garage) '
++ export CONDA_SHLVL=2
++ CONDA_SHLVL=2
++ export PATH=/opt/conda/envs/garage/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin
++ PATH=/opt/conda/envs/garage/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin
+ __conda_hashr
+ '[' -n '' ']'
+ '[' -n '' ']'
+ hash -r
+ pip install -r /root/code/garage/condaenv.3t3eiQ.requirements.txt
    Error [Errno 22] Invalid argument: '/opt/conda/envs/garage/bin/python' while executing command python setup.py egg_info
Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument: '/opt/conda/envs/garage/bin/python'

ERROR: Service 'garage-base' failed to build: The command '/bin/sh -c touch /root/.mujoco/mjkey.txt &&   conda env create -f /root/code/garage/environment.yml &&   rm -rf /opt/conda/pkgs/* &&   rm /root/.mujoco/mjkey.txt' returned a non-zero code: 1
Makefile:30: recipe for target 'build-headless' failed
make: *** [build-headless] Error 1

**Comment by ryanjulian** [comment] 2019-03-12 18:56
Hi Tung -- thanks for trying garage and reporting the error.

I tried `build-headless` on clean MacOS and Linux machines and was unable to reproduce your error. Our [builds on Docker Hub](https://hub.docker.com/r/rlworkgroup/garage-headless/builds) also appear to be healthy.

Since I wasn't able to reproduce your error, I will close this issue for now. **If the steps below don't work for you, please feel free to reopen the issue with more information.**

Here are some steps you can use to troubleshoot locally.

1. Try using the latest commit
    In order to help you debug, we need to know exactly which code you're running. What is the latest entry in `git log`? If it's not the latest commit, try running `git checkout master && git fetch origin && git rebase origin/master` and try again

2. Try rebuilding (and disable the cache)
Sometimes builds fail simply because a server used to retrieve packages was not responding, and that's usually fixed by just trying again.

     You can make sure you're building everything from scratch using the command (from the root of the repo)
    ```sh
    # equivalent to make build-headless, but with caching disabled
    docker-compose -f docker/docker-compose-headless.yml build --no-cache
    ```

**Closed by ryanjulian** 2019-03-12 18:56 UTC

**Comment by tunglm2203** [comment] 2019-03-14 08:56
Hi Ryan, sorry for replying late. I also face the same problem when building docker image as you recommend. I have tried several ways as follows:
1) Remove all the garage repository and clone again, try to build with your command suggest:
`docker-compose -f docker/docker-compose-headless.yml build --no-cache`
It failed at step 18/22: 
`Step 18/22 : RUN touch /root/.mujoco/mjkey.txt &&   conda env create -f /root/code/garage/environment.yml &&   rm -rf /opt/conda/pkgs/* &&   rm /root/.mujoco/mjkey.txt`
2) I saw that it is always broken when building image `rlworkgroup/garage-base`, at step 18/22 in `Dockerfile.base` file. So I have tried to build it separately, by use command (executing in root folder of repository): 
`docker build -f docker/Dockerfile.base .`
But it faces the same problem
3) I have tried install in my server, it's installed successfully (OS: Ubuntu 16.04)

Some information:
Version of repository: c4b49939df36487c49282ddb6bd9af647ea05b87
Local PC OS: Ubuntu 16.04
I already have Mujoco key

If you need any information, please let me know. Thank you!
