### ISSUE TITLE
Recurrent policies should support multiple hidden dimension in TensorFlow branch

### ISSUE THREAD

**Issue by ahtsan** [rlworkgroup/garage#1222] opened 2020-03-15 15:17 UTC
Currently, TF branch recurrent policies only support a single dimension (for example, see https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/policies/gaussian_gru_policy.py#L58).

**Comment by ryanjulian** [comment] 2020-03-16 19:50
Duplicate of #709

**Closed by ryanjulian** 2020-03-16 19:50 UTC
