### ISSUE TITLE
Pipenv install broken on pipenv v2020.5.28

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1453] opened 2020-05-29 03:15 UTC
This broke the CI

**Comment by ryanjulian** [comment] 2020-05-29 03:30
Not clear that #1423 is the root cause, because 2019.10 is also broken in a similar way https://travis-ci.com/github/rlworkgroup/garage/jobs/340842638

**Comment by gitanshu** [comment] 2020-05-29 09:34
Pipenv cut a new final release finally. That broke it :laughing: Will investigate the cause tomorrow

**Comment by gitanshu** [comment] 2020-05-29 21:54
#1458

**Comment by gitanshu** [comment] 2020-06-09 00:58
Closed by #1460

**Closed by gitanshu** 2020-06-09 00:58 UTC
Labels: bug
