### ISSUE TITLE
Metaworld example doesnt work

### ISSUE THREAD

**Issue by shagunsodhani** [rlworkgroup/garage#1970] opened 2020-08-25 23:20 UTC
python mtsac_metaworld_mt10.py
```
Traceback (most recent call last):
  File "mtsac_metaworld_mt10.py", line 7, in <module>
    import metaworld.benchmarks as mwb
ModuleNotFoundError: No module named 'metaworld.benchmarks'
```

```
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import metaworld
>>>
````

**Comment by avnishn** [comment] 2020-08-25 23:39
Hi @shagunsodhani, 

The reason why you're encountering this issue is because we are in the process of overhauling our MTRL and MetaRL examples to use the new Metaworld API that we released a month ago. 

We've written all of the code to make the necessary changes, however we are still in the process of benchmarking our algorithms to confirm no performance regressions.

If you want to use the examples in this repo, please use the commit of metaworld that is listed inside the garage setup.py.

That commit hash is: 861ae8d8c4bef80a7ed86f47f47acaa494d4ab77

Since I think I've solved the issue that you're having, I'm going to close this issue, but feel free to reopen and @ me (@avnishn) if you're having further trouble.

**Closed by avnishn** 2020-08-25 23:39 UTC

**Comment by shagunsodhani** [comment] 2020-08-26 00:41
Thanks for the prompt response.

**Comment by shagunsodhani** [comment] 2020-08-26 03:38
```
2020-08-25 20:15:49 | [mtsac_metaworld_mt10] Logging to /private/home/sodhani/projects/garage/examples/torch/data/local/experiment/mtsac_metaworld_mt10_7
/private/home/sodhani/projects/garage/src/garage/experiment/deterministic.py:37: UserWarning: Enabeling deterministic mode in PyTorch can have a performance impact when using GPU.
  'Enabeling deterministic mode in PyTorch can have a performance '
/private/home/sodhani/.conda/envs/garage/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
2020-08-25 20:20:21 | [mtsac_metaworld_mt10] Obtaining samples...
Traceback (most recent call last):
  File "mtsac_metaworld_mt10.py", line 102, in <module>
    mtsac_metaworld_mt10()
  File "/private/home/sodhani/.conda/envs/garage/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/private/home/sodhani/.conda/envs/garage/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/private/home/sodhani/.conda/envs/garage/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/private/home/sodhani/.conda/envs/garage/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/private/home/sodhani/projects/garage/src/garage/experiment/experiment.py", line 362, in __call__
    result = self.function(ctxt, **kwargs)
  File "mtsac_metaworld_mt10.py", line 99, in mtsac_metaworld_mt10
    runner.train(n_epochs=epochs, batch_size=batch_size)
  File "/private/home/sodhani/projects/garage/src/garage/experiment/local_runner.py", line 502, in train
    average_return = self._algo.train(self)
  File "/private/home/sodhani/projects/garage/src/garage/torch/algos/sac.py", line 209, in train
    last_return = self._evaluate_policy(runner.step_itr)
  File "/private/home/sodhani/projects/garage/src/garage/torch/algos/mtsac.py", line 186, in _evaluate_policy
    num_eps=self._num_evaluation_episodes))
  File "/private/home/sodhani/projects/garage/src/garage/np/_functions.py", line 60, in obtain_evaluation_episodes
    deterministic=deterministic)
  File "/private/home/sodhani/projects/garage/src/garage/sampler/utils.py", line 61, in rollout
    es = env.step(a)
  File "/private/home/sodhani/projects/garage/src/garage/envs/multi_env_wrapper.py", line 206, in step
    es = self._env.step(action)
  File "/private/home/sodhani/projects/garage/src/garage/envs/normalized_env.py", line 102, in step
    es = self._env.step(scaled_action)
  File "/private/home/sodhani/projects/garage/src/garage/envs/gym_env.py", line 214, in step
    observation, reward, done, info = self._env.step(action)
  File "/private/home/sodhani/.conda/envs/garage/lib/python3.7/site-packages/metaworld/envs/mujoco/multitask_env.py", line 161, in step
    obs, reward, done, info = self.active_env.step(action)
  File "/private/home/sodhani/.conda/envs/garage/lib/python3.7/site-packages/metaworld/envs/mujoco/sawyer_xyz/sawyer_reach_push_pick_place.py", line 147, in step
    self.do_simulation([action[-1], -action[-1]])
  File "/private/home/sodhani/.conda/envs/garage/lib/python3.7/site-packages/metaworld/envs/mujoco/mujoco_env.py", line 118, in do_simulation
    raise ValueError('Maximum path length allowed by the benchmark has been exceeded')
ValueError: Maximum path length allowed by the benchmark has been exceeded
```

**Comment by shagunsodhani** [comment] 2020-08-26 03:38
cc @avnishn

**Comment by ryanjulian** [comment] 2020-08-26 03:43
Please ensure max_episode_length of your algorithm has been set to 150 or less

**Comment by ryanjulian** [comment] 2020-08-26 03:48
If you need some more hands-on help, the community Slack would probably get you lower response times!

**Comment by shagunsodhani** [comment] 2020-08-26 03:55
Hi @ryanjulian :) Thanks for the prompt response. I should have been explicit, this error is thrown by the [example code (from this repo)](https://github.com/rlworkgroup/garage/blob/master/examples/torch/mtsac_metaworld_mt10.py). Hence I continued the conversation here :)

**Comment by shagunsodhani** [comment] 2020-08-26 03:56
I dont have the access to re-open the issue, hence I cc'd Avinash :)

**Comment by avnishn** [comment] 2020-08-26 04:24
I believe that your issue is caused by the bug where we were not specifying the max episode length of evaluation trajectories. 

A contributor opened a pr for this, and we're actively trying to merge it (#1952). 

In the meantime, please cherry pick the commit from this or into your branch, or make the one line change that is necessary. 

I'll make sure that bugs like this are gone within the week. 

Avnish

**Comment by shagunsodhani** [comment] 2020-08-26 10:12
Thanks a lot @avnishn
