### ISSUE TITLE
MTSAC not learning

### ISSUE THREAD

**Issue by zfang399** [rlworkgroup/garage#2028] opened 2020-09-07 05:19 UTC
@avnishn 
Hi! Thank you for developing and maintaining this great repo. It makes developing and benchmarking models so much easier.

I am trying to run the baseline MTSAC on metaworld mt10 and mt50. However, it seems that the model is not learning anything (the success rate and return for each task are not changing much). For mt10, the success rate remains 0 at 3.6e+06 env steps / iteration 90 (with an average return of 3.08112). I'm observing similar things for mt50. Have you run into similar problems and do you have any suggestions on how I can approach those problems?

I am using the `2020-06` release of garage (installed from pip), with the correct metaworld version (the one provided in `setup.py`. The example scripts I'm using are from the 2020-06 release branch of the repo. The only thing I changed in the code was in `python3.6/site-packages/garage/torch/algos/sac.py` line 202, where I changed the `is` in the assert to a `==`, due to an error at the runtime of `mtsac_metaworld_mt10.py`, which should not affect the algorithm's performance. I also tested the `sac_half_cheetah_batch.py`, which trains normally as the return goes to a few thousand after some iterations.

Thanks a lot for your help! Please let me know if there's anything unclear in my description, or if you need any other information about this problem.

**Comment by avnishn** [comment] 2020-09-07 16:31
Hey @zfang399, thanks for checking out garage!

There's a few fixes that we are currently attempting to backport onto SAC and MTSAC, and you can find the pr where I do that here: https://github.com/rlworkgroup/garage/pull/2002

Can you rebase your branch onto those changes and let me know if that solves your problem?

Thanks!
Avnish Narayan

**Comment by zfang399** [comment] 2020-09-07 19:59
Hi Avnish, thanks for the reply!

I tried switching to the `2020.06-fix_various_sac_mtsac_bugs_backport` branch, but it still gives me similar behaviors --- SAC runs correctly, but the MTSAC mt10 returns aren't changing (~32 for the reach-v1 task and ~negative 0.2 for all other tasks).

I also tried setting the reward normalization to False as suggested in #1561 but it didn't help either. Does `mtsac_metaworld_mt10.py` work on your end? If so, could you point me to the branch of garage you're using? Thanks a lot!

**Comment by avnishn** [comment] 2020-09-08 02:17
@zfang399 Garage automatically generates tensor board log files. Can you go ahead and use [tensorboard.dev](https://tensorboard.dev) to upload some of your experiments and link them here?

**Comment by zfang399** [comment] 2020-09-08 02:28
@avnishn sure, here's the mtsac_metaworld_mt10 experiment (the one that's not learning): https://tensorboard.dev/experiment/pHadIgeSQg21cr8rGfPXpw/

here's the sac_half_cheetah_batch experiment (which learns normally): https://tensorboard.dev/experiment/UR1GE11HRXuP4YqzlfVsWQ/

**Comment by avnishn** [comment] 2020-09-08 05:05
There must be something wrong with how done signals are handled in this Garage release, or possibly you are using the incorrect Metaworld version somehow.

I was able to tell this because the completion rate of your eval trajectories is 1. That implies that each one of your eval trajectories ends with a done=True signal, or that your environment terminates. This however can't be the case in the correct situation, because versions of Metaworld starting in February or March stopped returning a done=True signal. 

In the meantime, I ran the version of MTSAC on the master branch, with the version of Metaworld that you can install using our setup.py, by running `pip install -e .[dev]` in your development environment, and these were my results:

https://tensorboard.dev/experiment/W5FRqD9BSymoofqvt7S1eg/#scalars

**I'll inspect the release 2020.06 branch and get back to you, but in the meantime, please switch the version that we are currently using on master, as I have verified that it works.**

As always, let me know if you have any questions by @ ing me, I'm more than happy to be of help!

Best,
Avnish

**Comment by zfang399** [comment] 2020-09-08 05:28
Hi Avnish, thank you so much for your help! This is a super helpful answer!

I will try switching to the version on master and re-install metaworld. I'll let you know if I have any other questions!

Best,
Andy

**Comment by avnishn** [comment] 2020-09-08 17:34
Hey @zfang399 it seems that you were right, there is a bug on our 2020.06 release that is causing some perceived performance regression. I'm going to inspect it this week and generate a back port. Thanks for bringing this up!

**Comment by zfang399** [comment] 2020-09-08 22:41
Hi @avnishn thanks for letting me know! And your suggestion of going to the master's branch worked!

**Comment by avnishn** [comment] 2020-09-08 22:44
@zfang399 I've opened a backport onto 2020.06 that fixes the problem. I'll respond here and tag you again when we cut the updated 2020.06 release with changes to pypi.

**Comment by ryanjulian** [comment] 2020-09-09 21:12
@avnishn does this affect master too, or only `release-2020.06`?

**Comment by avnishn** [comment] 2020-09-09 22:09
I benchmarked performance on master and then didn't observe the same issues. I think this may have been resolved during the Garage->GymEnv transition.

**Comment by ryanjulian** [comment] 2020-09-09 22:12
....but does the root cause exist on master or not? please write a test which detects the error and see if it passes on master.

**Comment by avnishn** [comment] 2020-09-11 23:09
@zfang399 we merged #2029 and your problems should be fixed! I'm going to close this for now.

Avnish

**Closed by avnishn** 2020-09-11 23:09 UTC
Labels: backport-to-2020.06, bug
