### ISSUE TITLE
Cannot find setup_linux.sh after installing some dependencies

### ISSUE THREAD

**Issue by FarnazAdib** [rlworkgroup/garage#559] opened 2019-03-05 14:03 UTC
I am trying to install garage on Ubuntu 18.04 using [express installation](https://rlgarage.readthedocs.io/en/latest/user/installation.html#):
`./scripts/setup_linux.sh --mjkey path-to-your-mjkey.txt --modify-bashrc`

I run the above command in the garage root directory. So, it starts installing dependencies but after a while I receive this message and I assume that the installation stops.

> ./scripts/setup_linux.sh: line 190: : No such file or directory

The whole log is given below:

> Installing garage dependencies
> You will probably be asked for your sudo password
> Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
> Hit:2 http://dl.google.com/linux/chrome/deb stable Release
> Hit:3 http://se.archive.ubuntu.com/ubuntu bionic InRelease
> Get:4 http://se.archive.ubuntu.com/ubuntu bionic-updates InRelease [88,7 kB]
> Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88,7 kB]
> Get:6 http://se.archive.ubuntu.com/ubuntu bionic-backports InRelease [74,6 kB]
> Get:8 http://se.archive.ubuntu.com/ubuntu bionic-updates/main amd64 DEP-11 Metadata [278 kB]
> Get:9 http://se.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 48x48 Icons [66,7 kB]
> Get:10 http://se.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 64x64 Icons [123 kB]
> Get:11 http://se.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 DEP-11 Metadata [202 kB]
> Get:12 http://se.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 48x48 Icons [188 kB]
> Get:13 http://se.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 64x64 Icons [355 kB]
> Get:14 http://se.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 DEP-11 Metadata [2 468 B]
> Get:15 http://se.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 DEP-11 Metadata [7 356 B]
> Fetched 1 474 kB in 1s (1 667 kB/s)
> Reading package lists...
> Building dependency tree...
> Reading state information...
> 20 packages can be upgraded. Run 'apt list --upgradable' to see them.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> bzip2 is already the newest version (1.0.6-8.1).
> cmake is already the newest version (3.10.2-1ubuntu2).
> libjpeg-dev is already the newest version (8c-2ubuntu8).
> unzip is already the newest version (6.0-21ubuntu1).
> libglew-dev is already the newest version (2.0.0-5).
> libopenmpi-dev is already the newest version (2.1.1-8).
> openmpi-bin is already the newest version (2.1.1-8).
> patchelf is already the newest version (0.9-1).
> swig is already the newest version (3.0.12-1).
> git is already the newest version (1:2.17.1-1ubuntu0.4).
> libosmesa6-dev is already the newest version (18.2.2-0ubuntu1~18.04.2).
> libpq-dev is already the newest version (10.6-0ubuntu0.18.04.1).
> wget is already the newest version (1.19.4-1ubuntu2.1).
> xorg-dev is already the newest version (1:7.7+19ubuntu7.1).
> ffmpeg is already the newest version (7:3.4.4-0ubuntu0.18.04.1).
> libsdl2-dev is already the newest version (2.0.8+dfsg1-1ubuntu1.18.04.1).
> 0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Note, selecting 'libglfw-dev' for glob 'libglfw*'
> Note, selecting 'libglfw3-wayland' for glob 'libglfw*'
> Note, selecting 'libglfw3' for glob 'libglfw*'
> Note, selecting 'libglfw3-dev' for glob 'libglfw*'
> Note, selecting 'libglfw3-doc' for glob 'libglfw*'
> Package 'libglfw-dev' is not installed, so not removed
> Package 'libglfw3' is not installed, so not removed
> Package 'libglfw3-dev' is not installed, so not removed
> Package 'libglfw3-doc' is not installed, so not removed
> Package 'libglfw3-wayland' is not installed, so not removed
> 0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
> Cloning into '/tmp/tmp.LBxvW5rndP/glfw'...
> remote: Enumerating objects: 4, done.
> remote: Counting objects: 100% (4/4), done.
> remote: Compressing objects: 100% (3/3), done.
> remote: Total 23249 (delta 3), reused 1 (delta 1), pack-reused 23245
> Receiving objects: 100% (23249/23249), 11.49 MiB | 8.24 MiB/s, done.
> Resolving deltas: 100% (16294/16294), done.
> Note: checking out '0be4f3f75aebd9d24583ee86590a38e741db0904'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at 0be4f3f7 Add GLFW_FOCUS_ON_SHOW window hint and attribute
> -- The C compiler identification is GNU 7.3.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
> -- Using X11 for window creation
> -- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
> -- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
> -- Looking for gethostbyname
> -- Looking for gethostbyname - found
> -- Looking for connect
> -- Looking for connect - found
> -- Looking for remove
> -- Looking for remove - found
> -- Looking for shmat
> -- Looking for shmat - found
> -- Looking for IceConnectionNumber in ICE
> -- Looking for IceConnectionNumber in ICE - found
> -- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /tmp/tmp.LBxvW5rndP/glfw/glfw-build
> Scanning dependencies of target glfw
> [ 17%] Building C object src/CMakeFiles/glfw.dir/monitor.c.o
> [ 17%] Building C object src/CMakeFiles/glfw.dir/input.c.o
> [ 17%] Building C object src/CMakeFiles/glfw.dir/window.c.o
> [ 23%] Building C object src/CMakeFiles/glfw.dir/vulkan.c.o
> [ 29%] Building C object src/CMakeFiles/glfw.dir/x11_monitor.c.o
> [ 35%] Building C object src/CMakeFiles/glfw.dir/init.c.o
> [ 41%] Building C object src/CMakeFiles/glfw.dir/x11_init.c.o
> [ 47%] Building C object src/CMakeFiles/glfw.dir/context.c.o
> [ 70%] Building C object src/CMakeFiles/glfw.dir/posix_thread.c.o
> [ 70%] Building C object src/CMakeFiles/glfw.dir/xkb_unicode.c.o
> [ 70%] Building C object src/CMakeFiles/glfw.dir/posix_time.c.o
> [ 70%] Building C object src/CMakeFiles/glfw.dir/x11_window.c.o
> [ 76%] Building C object src/CMakeFiles/glfw.dir/glx_context.c.o
> [ 82%] Building C object src/CMakeFiles/glfw.dir/egl_context.c.o
> [ 88%] Building C object src/CMakeFiles/glfw.dir/osmesa_context.c.o
> [ 94%] Building C object src/CMakeFiles/glfw.dir/linux_joystick.c.o
> [100%] Linking C shared library libglfw.so
> [100%] Built target glfw
> [100%] Built target glfw
> Install the project...
> -- Install configuration: ""
> -- Up-to-date: /usr/local/include/GLFW
> -- Installing: /usr/local/include/GLFW/glfw3native.h
> -- Installing: /usr/local/include/GLFW/glfw3.h
> -- Installing: /usr/local/lib/cmake/glfw3/glfw3Config.cmake
> -- Installing: /usr/local/lib/cmake/glfw3/glfw3ConfigVersion.cmake
> -- Installing: /usr/local/lib/cmake/glfw3/glfw3Targets.cmake
> -- Installing: /usr/local/lib/cmake/glfw3/glfw3Targets-noconfig.cmake
> -- Installing: /usr/local/lib/pkgconfig/glfw3.pc
> -- Installing: /usr/local/lib/libglfw.so.3.3
> -- Up-to-date: /usr/local/lib/libglfw.so.3
> -- Up-to-date: /usr/local/lib/libglfw.so
> MuJoCo is already installed./scripts/setup_linux.sh: line 190: : No such file or directory
> 

Would you please let me know what the problem is and how I can solve it?
Thanks!

**Comment by gonzaiva** [comment] 2019-03-05 21:59
Hi @FarnazAdib, the problem is [here](https://github.com/rlworkgroup/garage/blob/master/scripts/setup_linux.sh#L190).
The environment variable BASH_PROF is not defined in the setup script for linux, so the append operator (>>) will fail because the variable doesn't expand in a valid file path.
The correct variable to use here is BASH_RC, and this is a bug on our side, so we'll push a fix for this asap. Thanks for the letting us know.

**Comment by gonzaiva** [comment] 2019-03-06 02:11
@ryanjulian this does not apply to v2018.10, since the issue was introduced in v2019.02.
@FarnazAdib, please set your local repo at the tip of the release-2019.02 branch, and let us know if this solved the issue.

**Closed** 2019-03-06 03:08 UTC
Labels: bug

**Comment by FarnazAdib** [comment] 2019-03-06 08:11
@gonzaiva Thanks for your quick response! It solved the problem.
